package dao;

import dao.po.TTask;
import dao.po.TTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int countByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int deleteByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Delete({
        "delete from t_task",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Insert({
        "insert into t_task (title, content, ",
        "starttime, endtime, ",
        "estimate, position, ",
        "creator, actor, urgent, ",
        "importance, done, completetime)",
        "values (#{title,jdbcType=CHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{starttime,jdbcType=TIMESTAMP}, #{endtime,jdbcType=TIMESTAMP}, ",
        "#{estimate,jdbcType=REAL}, #{position,jdbcType=VARCHAR}, ",
        "#{creator,jdbcType=CHAR}, #{actor,jdbcType=CHAR}, #{urgent,jdbcType=BIT}, ",
        "#{importance,jdbcType=BIT}, #{done,jdbcType=BIT}, #{completetime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int insertSelective(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    List<TTask> selectByExample(TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Select({
        "select",
        "id, title, content, starttime, endtime, estimate, position, creator, actor, ",
        "urgent, importance, done, completetime",
        "from t_task",
        "where id = #{id,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") TTask record, @Param("example") TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExample(@Param("record") TTask record, @Param("example") TTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByPrimaryKeySelective(TTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Update({
        "update t_task",
        "set title = #{title,jdbcType=CHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "starttime = #{starttime,jdbcType=TIMESTAMP},",
          "endtime = #{endtime,jdbcType=TIMESTAMP},",
          "estimate = #{estimate,jdbcType=REAL},",
          "position = #{position,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=CHAR},",
          "actor = #{actor,jdbcType=CHAR},",
          "urgent = #{urgent,jdbcType=BIT},",
          "importance = #{importance,jdbcType=BIT},",
          "done = #{done,jdbcType=BIT},",
          "completetime = #{completetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TTask record);
}