package dao;

import dao.po.TTeamtask;
import dao.po.TTeamtaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TTeamtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int countByExample(TTeamtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int deleteByExample(TTeamtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Delete({
        "delete from t_teamtask",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Insert({
        "insert into t_teamtask (teamid, taskid)",
        "values (#{teamid,jdbcType=CHAR}, #{taskid,jdbcType=CHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(TTeamtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int insertSelective(TTeamtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    List<TTeamtask> selectByExample(TTeamtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Select({
        "select",
        "id, teamid, taskid",
        "from t_teamtask",
        "where id = #{id,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TTeamtask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") TTeamtask record, @Param("example") TTeamtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExample(@Param("record") TTeamtask record, @Param("example") TTeamtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByPrimaryKeySelective(TTeamtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Update({
        "update t_teamtask",
        "set teamid = #{teamid,jdbcType=CHAR},",
          "taskid = #{taskid,jdbcType=CHAR}",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TTeamtask record);
}