package dao;

import dao.po.TTeam;
import dao.po.TTeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int countByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int deleteByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Delete({
        "delete from t_team",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Insert({
        "insert into t_team (creator, team, ",
        "description)",
        "values (#{creator,jdbcType=CHAR}, #{team,jdbcType=CHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int insertSelective(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    List<TTeam> selectByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Select({
        "select",
        "id, creator, team, description",
        "from t_team",
        "where id = #{id,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TTeam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") TTeam record, @Param("example") TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByExample(@Param("record") TTeam record, @Param("example") TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    int updateByPrimaryKeySelective(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    @Update({
        "update t_team",
        "set creator = #{creator,jdbcType=CHAR},",
          "team = #{team,jdbcType=CHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TTeam record);
}