package dao.po;

public class TTaskmember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskmember.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskmember.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taskmember.userid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taskmember
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTaskmember(String id, String teamid, String userid) {
        this.id = id;
        this.teamid = teamid;
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taskmember
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTaskmember() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskmember.id
     *
     * @return the value of t_taskmember.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskmember.id
     *
     * @param id the value for t_taskmember.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskmember.teamid
     *
     * @return the value of t_taskmember.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskmember.teamid
     *
     * @param teamid the value for t_taskmember.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taskmember.userid
     *
     * @return the value of t_taskmember.userid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taskmember.userid
     *
     * @param userid the value for t_taskmember.userid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}