package dao.po;

import java.util.Date;

public class TTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.title
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.content
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.starttime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.endtime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.estimate
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Float estimate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.position
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.actor
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String actor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.urgent
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Boolean urgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.importance
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Boolean importance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.done
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Boolean done;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.completetime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private Date completetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTask(String id, String title, String content, Date starttime, Date endtime, Float estimate, String position, String creator, String actor, Boolean urgent, Boolean importance, Boolean done, Date completetime) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.starttime = starttime;
        this.endtime = endtime;
        this.estimate = estimate;
        this.position = position;
        this.creator = creator;
        this.actor = actor;
        this.urgent = urgent;
        this.importance = importance;
        this.done = done;
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.id
     *
     * @return the value of t_task.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.id
     *
     * @param id the value for t_task.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.title
     *
     * @return the value of t_task.title
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.title
     *
     * @param title the value for t_task.title
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.content
     *
     * @return the value of t_task.content
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.content
     *
     * @param content the value for t_task.content
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.starttime
     *
     * @return the value of t_task.starttime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.starttime
     *
     * @param starttime the value for t_task.starttime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.endtime
     *
     * @return the value of t_task.endtime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.endtime
     *
     * @param endtime the value for t_task.endtime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.estimate
     *
     * @return the value of t_task.estimate
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Float getEstimate() {
        return estimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.estimate
     *
     * @param estimate the value for t_task.estimate
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setEstimate(Float estimate) {
        this.estimate = estimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.position
     *
     * @return the value of t_task.position
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.position
     *
     * @param position the value for t_task.position
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.creator
     *
     * @return the value of t_task.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.creator
     *
     * @param creator the value for t_task.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.actor
     *
     * @return the value of t_task.actor
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.actor
     *
     * @param actor the value for t_task.actor
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.urgent
     *
     * @return the value of t_task.urgent
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Boolean getUrgent() {
        return urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.urgent
     *
     * @param urgent the value for t_task.urgent
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setUrgent(Boolean urgent) {
        this.urgent = urgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.importance
     *
     * @return the value of t_task.importance
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Boolean getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.importance
     *
     * @param importance the value for t_task.importance
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setImportance(Boolean importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.done
     *
     * @return the value of t_task.done
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Boolean getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.done
     *
     * @param done the value for t_task.done
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setDone(Boolean done) {
        this.done = done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.completetime
     *
     * @return the value of t_task.completetime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.completetime
     *
     * @param completetime the value for t_task.completetime
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }
}