package dao.po;

public class TTeamtask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teamtask.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teamtask.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teamtask.taskid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String taskid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTeamtask(String id, String teamid, String taskid) {
        this.id = id;
        this.teamid = teamid;
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teamtask
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTeamtask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teamtask.id
     *
     * @return the value of t_teamtask.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teamtask.id
     *
     * @param id the value for t_teamtask.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teamtask.teamid
     *
     * @return the value of t_teamtask.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teamtask.teamid
     *
     * @param teamid the value for t_teamtask.teamid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teamtask.taskid
     *
     * @return the value of t_teamtask.taskid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teamtask.taskid
     *
     * @param taskid the value for t_teamtask.taskid
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }
}