package dao.po;

public class TTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team.team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team.description
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTeam(String id, String creator, String team, String description) {
        this.id = id;
        this.creator = creator;
        this.team = team;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public TTeam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team.id
     *
     * @return the value of t_team.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team.id
     *
     * @param id the value for t_team.id
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team.creator
     *
     * @return the value of t_team.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team.creator
     *
     * @param creator the value for t_team.creator
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team.team
     *
     * @return the value of t_team.team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team.team
     *
     * @param team the value for t_team.team
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team.description
     *
     * @return the value of t_team.description
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team.description
     *
     * @param description the value for t_team.description
     *
     * @mbggenerated Sun Jul 01 14:21:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}